### ISSUE TITLE
App crashes with a latest available ammo files

### ISSUE THREAD

**Issue by rayrapetyan** [AterCattus/highloadcup_tester#3]
[holuser@docker ~]$ $GOBIN/hl_tester -addr http://127.0.0.1:8080 -hlcupdocs hlcupdocs/data/FULL/ -test -phase 2
bullets count: 353
Start test run
panic: Wrong block header line#3531: POST /users/66894?query_id=353 HTTP/1.1: Cannot parse ammo file

goroutine 7 [running]:
panic(0x689aa0, 0xc420266060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.loadDataRequests.func1(0xc420030050, 0xc4200723c0)
	/home/holuser/projects/src/hl_tester.go:171 +0x80c
created by main.loadDataRequests
	/home/holuser/projects/src/hl_tester.go:220 +0xe6

**Comment by atercattus** [comment]
Исправлено в
https://github.com/AterCattus/highloadcup_tester/commit/e9ad8010f32a52a8471e4a640b25c6105262af29
