### ISSUE TITLE
ошибка с GOPATH

### ISSUE THREAD

**Issue by Sammers21** [AterCattus/highloadcup_tester#4]
![image](https://user-images.githubusercontent.com/16746106/29705504-f181852c-8986-11e7-868d-73908ead67c2.png)

**Comment by Sammers21** [comment]
![image](https://user-images.githubusercontent.com/16746106/29705560-4d47b25a-8987-11e7-9490-afc09320ec76.png)

**Comment by Sammers21** [comment]
что не так у меня?

**Comment by vearutop** [comment]
Правильный путь: `$GOPATH/src/github.com/AterCattus/highloadcup_tester`
